export const workExperience = [
  {
    company: "Iati",
    role: "Product Marketing",
    startDate: "2021-01-01",
    endDate: "2021-06-01",
    description: ["Figma", "Adobe after effects", "Email marketing", "Sales"],
    location: "Antalya, Turkiye",
    logo: "/logos/iati.jpeg",
  },
  {
    company: "Feen",
    role: "Product Design",
    startDate: "2021-01-01",
    endDate: "2021-06-01",
    description: [
      "Google Analytics",
      "Google Adsense",
      "Facebook & Instagram Ads",
      "Adobe after effects",
      "Figma",
    ],
    location: "Izmir, Turkiye",
    logo: "/logos/feen.png",
  },
  {
    company: "LaykaDAO",
    role: "Community Builder",
    startDate: "2022-01-01",
    endDate: "2023-06-01",
    description: ["Content marketing", "Community management"],
    location: "Global",
    logo: "/logos/luna.jpeg",
  },
  {
    company: "Growtechie",
    role: "Frontend Developer",
    startDate: "2024-04-04",
    endDate: "-",
    description: [
      "Building e-learning platform for people who wants to learn tech",
      "We are building it for the India and Turkiye",
      "We are using modern tools like Nextjs, React and Firebase",
    ],
    location: "India, Turkiye",
    logo: "/logos/growtechie.jpeg",
  },
];
